port: 8989
socks-port: 1080
mixed-port: 8080
allow-lan: true
bind-address: '*'
ipv6: false
mode: rule
log-level: silent
geodata-mode: true
tcp-concurrent: true
dns:
  enable: true
  listen: 0.0.0.0:9090
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  use-hosts: true
  enhanced-mode: redir-host
  nameserver:
    - 8.8.8.8
    - 8.8.4.4
    - https://dns.google/dns-query
    - tls://dns.google:853
  fallback:
    - 1.1.1.1
    - 1.0.0.1
    - https://dns.cloudflare.com/dns-query
    - tls://1dot1dot1dot1.cloudflare-dns.com:853
proxies: 
# -----------------------------------------------------------
# Vmess/Vmess gRPC
# -----------------------------------------------------------
  - name: ID Mainssh # Exp 18
    server: 104.26.4.10
    port: 443
    type: vmess
    uuid: 19315fcf-0f5d-4ece-8b0f-c8296832dd4a
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: "idmgrpc.mainssh.xyz"
    network: grpc
    grpc-opts:
      grpc-service-name: vmessgrpc
    udp: true
# -----------------------------------------------------------
  - name: SG Sshkit # Exp 14 Sept
    server: 104.26.4.10
    port: 80
    type: vmess
    uuid: c6747da4-fb2e-4a2a-bdb7-8614bdd6b0b3
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg1-v2ray.sshkit.org
    network: ws
    ws-opts:
      path: /sshkit/5520010979/62f8aae81354f/
      headers:
        Host: sg1-v2ray.sshkit.org
    udp: true
  - name: ID-IKD
    server: idtj-ikd.bonds.id
    port: 443
    type: trojan
    password: 45e0f150-1c92-11ed-9031-1239d0255272
    skip-cert-verify: true
    sni: web.web.whatsapp.com
    udp: true
#=============================================
  - name: SG-MUX
    server: sg6-trojan.bonds.id
    port: 443
    type: trojan
    password: 81e9f5f0-1c92-11ed-8d18-1239d0255272
    skip-cert-verify: true
    sni: web.web.whatsapp.com
    udp: true
#=============================================
  - name: SG-UDPGW
    server: sg8-trojan.bonds.id
    port: 443
    type: trojan
    password: a2940130-1c92-11ed-aebe-1239d0255272
    skip-cert-verify: true
    sni: web.web.whatsapp.com
    udp: true
#=============================================
  - name: ID-BIZNET I
    server: id5-trojan.bonds.id
    port: 443
    type: trojan
    password: ca0c33d0-1c92-11ed-9a11-1239d0255272
    skip-cert-verify: true
    sni: web.web.whatsapp.com
    udp: true
#=============================================
  - name: SG-HE II
    server: sg2-trojan.bonds.id
    port: 443
    type: trojan
    password: f1a23bf0-1c92-11ed-b6d8-1239d0255272
    skip-cert-verify: true
    sni: web.web.whatsapp.com
    udp: true
#=============================================
  - name: ID-BIZNET II
    server: id2-trojan.bonds.id
    port: 443
    type: trojan
    password: 200b3f20-1c93-11ed-9472-1239d0255272
    skip-cert-verify: true
    sni: web.web.whatsapp.com
    udp: true
#=============================================
  - name: SG-HE III
    server: sg3-trojan.bonds.id
    port: 443
    type: trojan
    password: 4717af60-1c93-11ed-9315-1239d0255272
    skip-cert-verify: true
    sni: web.web.whatsapp.com
    udp: true
#=============================================
  - name: ID-HERZA
    server: idtj-herza.bonds.id
    port: 443
    type: trojan
    password: 6ae7c990-1c93-11ed-a6f2-1239d0255272
    skip-cert-verify: true
    sni: web.web.whatsapp.com
    udp: true
#=============================================
  - name: SG-OVH
    server: 104.26.4.10
    port: 443
    type: trojan
    password: 888f4b20-1c93-11ed-8403-1239d0255272
    skip-cert-verify: true
    sni: sgovh-trojan.bonds.id
    udp: true
#=============================================
  - name: SG-HE I
    server: 104.26.4.10
    port: 443
    type: trojan
    password: a1647ec0-1c93-11ed-bfc5-1239d0255272
    skip-cert-verify: true
    sni: sg1-trojan.bonds.id
    udp: true
#=============================================
# -----------------------------------------------------------
# Proxy Group
# -----------------------------------------------------------
proxy-groups:
  - name: Proxy
    type: select
    proxies:
       - ID Mainssh
       - SG Sshkit
       - ID-IKD
       - SG-MUX
       - SG-UDPGW
       - ID-BIZNET I
       - SG-HE II
       - ID-BIZNET II
       - SG-HE III
       - ID-HERZA
       - SG-OVH
       - SG-HE I
# -----------------------------------------------------------
rules:
  - MATCH,Proxy
#----------------------------------------------------------
