port: 8989
socks-port: 1080
mixed-port: 8080
allow-lan: true
bind-address: '*'
ipv6: false
mode: rule
log-level: silent
geodata-mode: true
tcp-concurrent: true
dns:
  enable: true
  listen: 0.0.0.0:9090
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  use-hosts: true
  enhanced-mode: redir-host
  nameserver:
    - 8.8.8.8
    - 8.8.4.4
    - https://dns.google/dns-query
    - tls://dns.google:853
  fallback:
    - 1.1.1.1
    - 1.0.0.1
    - https://dns.cloudflare.com/dns-query
    - tls://1dot1dot1dot1.cloudflare-dns.com:853
proxies: 
# -----------------------------------------------------------
# Vmess/Vmess gRPC
# -----------------------------------------------------------
  - name: ID Mainssh # Exp 18
    server: 104.26.4.10
    port: 443
    type: vmess
    uuid: 19315fcf-0f5d-4ece-8b0f-c8296832dd4a
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: "idmgrpc.mainssh.xyz"
    network: grpc
    grpc-opts:
      grpc-service-name: vmessgrpc
    udp: true
# -----------------------------------------------------------
  - name: SG Sshkit # Exp 14 Sept
    server: 104.26.4.10
    port: 80
    type: vmess
    uuid: c6747da4-fb2e-4a2a-bdb7-8614bdd6b0b3
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg1-v2ray.sshkit.org
    network: ws
    ws-opts:
      path: /sshkit/5520010979/62f8aae81354f/
      headers:
        Host: sg1-v2ray.sshkit.org
    udp: true
# -----------------------------------------------------------
# Proxy Group
# -----------------------------------------------------------
proxy-groups:
  - name: IRENE
    type: select
    proxies:
       - ID Mainssh
       - SG Sshkit
# -----------------------------------------------------------
rules:
  - MATCH,IRENE
#----------------------------------------------------------
