port: 8989
socks-port: 1080
mixed-port: 8080
allow-lan: true
bind-address: '*'
ipv6: false
mode: rule
log-level: silent
geodata-mode: true
tcp-concurrent: true
dns:
  enable: true
  listen: 0.0.0.0:9090
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  use-hosts: true
  enhanced-mode: redir-host
  nameserver:
    - 8.8.8.8
    - 8.8.4.4
    - https://dns.google/dns-query
    - tls://dns.google:853
  fallback:
    - 1.1.1.1
    - 1.0.0.1
    - https://dns.cloudflare.com/dns-query
    - tls://1dot1dot1dot1.cloudflare-dns.com:853
proxies: 
# -----------------------------------------------------------
# Vmess/Vmess gRPC
# -----------------------------------------------------------
  - name: ID Mainssh # Exp 18
    server: 104.26.4.10
    port: 443
    type: vmess
    uuid: 19315fcf-0f5d-4ece-8b0f-c8296832dd4a
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: "idmgrpc.mainssh.xyz"
    network: grpc
    grpc-opts:
      grpc-service-name: vmessgrpc
    udp: true
# -----------------------------------------------------------
  - name: SG Mainssh # Exp 18
    server: 104.26.4.10
    port: 443
    type: vless
    uuid: d47d74b9-29de-44c9-b22a-22d9a82dfe36
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: "sglgrpc.mainssh.xyz"
    network: grpc
    grpc-opts:
      grpc-service-name: vlessgrpc
    udp: true
# -----------------------------------------------------------
# Akun Trojan
# -----------------------------------------------------------
  - name: ID Biznet II
    server: 104.26.4.10
    port: 443
    type: trojan
    password: f6293760-1a0b-11ed-a14d-1239d0255272
    skip-cert-verify: true
    sni: "id2-trojan.bonds.id"
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: "id2-trojan.bonds.id"
    udp: true
# -----------------------------------------------------------
  - name: ID Biznet I
    server: 104.26.4.10
    port: 443
    type: trojan
    password: 2011d2a0-1a0c-11ed-9bac-1239d0255272
    skip-cert-verify: true
    sni: "id5-trojan.bonds.id"
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: "id5-trojan.bonds.id"
    udp: true
# -----------------------------------------------------------
# Proxy Group
# -----------------------------------------------------------
proxy-groups:
  - name: IRENE
    type: select
    proxies:
      - GRPC
      - TROJAN/GO/GFW
# -----------------------------------------------------------
  - name: GRPC
    type: select
    proxies:
      - ID Mainssh
      - SG Mainssh
# -----------------------------------------------------------
  - name: TROJAN/GO/GFW
    type: select
    proxies:
      - ID Biznet I
      - ID Biznet II
# -----------------------------------------------------------
rules:
  - MATCH,IRENE
#----------------------------------------------------------
